server:
  port: 8080

spring:
  application:
    name: springboot-mock-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000
      minimum-idle: 5
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  jackson:
    serialization:
      write-dates-as-timestamps: true
    property-naming-strategy: SNAKE_CASE
mybatis-plus:
  mapper-locations: ["classpath*:/mapper/**/*.xml"]
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
